import { Router, type IRouter } from "express";
import path from "path";
import healthRouter from "./health.js";
import productsRouter from "./products.js";
import categoriesRouter from "./categories.js";
import cartRouter from "./cart.js";
import ordersRouter from "./orders.js";
import authRouter from "./auth.js";
import wishlistRouter from "./wishlist.js";
import reviewsRouter from "./reviews.js";
import promoRouter from "./promo.js";
import adminRouter from "./admin.js";
import settingsRouter from "./settings.js";
import uploadsRouter from "./uploads.js";
const router: IRouter = Router();

router.use(healthRouter);
router.use("/products", productsRouter);
router.use("/categories", categoriesRouter);
router.use("/cart", cartRouter);
router.use("/orders", ordersRouter);
router.use("/auth", authRouter);
router.use("/wishlist", wishlistRouter);
router.use("/reviews", reviewsRouter);
router.use("/promo", promoRouter);
router.use("/admin", adminRouter);
router.use("/settings", settingsRouter);
router.use("/products", uploadsRouter);

export default router;
