import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import productsRouter from "./products.js";
import categoriesRouter from "./categories.js";
import cartRouter from "./cart.js";
import ordersRouter from "./orders.js";
import authRouter from "./auth.js";
import wishlistRouter from "./wishlist.js";
import reviewsRouter from "./reviews.js";
import promoRouter from "./promo.js";
import adminRouter from "./admin.js";
import adminsRouter from "./admins.js";
import settingsRouter from "./settings.js";
import uploadsRouter from "./uploads.js";
import profileRouter from "./profile.js";
import contactRouter from "./contact.js";
import couponsUserRouter from "./coupons-user.js";
import adminCouponsRouter from "./admin-coupons.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/products", productsRouter);
router.use("/categories", categoriesRouter);
router.use("/cart", cartRouter);
router.use("/orders", ordersRouter);
router.use("/auth", authRouter);
router.use("/wishlist", wishlistRouter);
router.use("/reviews", reviewsRouter);
router.use("/promo", promoRouter);
router.use("/admin", adminRouter);
router.use("/admin/admins", adminsRouter);
router.use("/admin/coupons", adminCouponsRouter);
router.use("/settings", settingsRouter);
router.use("/products", uploadsRouter);
router.use("/profile", profileRouter);
router.use("/contact", contactRouter);
router.use("/coupons", couponsUserRouter);

export default router;
